name: Build Singlearch ARM64

on:
  push:
    branches: [ main ]
    paths: [ 'i2c-addon-ver1/**' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Get version from config.yaml
        run: |
          sudo wget -qO /usr/local/bin/yq https://github.com/mikefarah/yq/releases/latest/download/yq_linux_amd64
          sudo chmod +x /usr/local/bin/yq
          ADDON_VERSION=$(yq -r '.version' ./addon/config.yaml)
          echo "Version is: $ADDON_VERSION"

      - name: Build singlearch ARM64
        run: |
          docker build \
            --platform linux/arm64/v8 \
            --build-arg BUILD_FROM=debian:bookworm-slim \
            -t ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/addon:${{ env.ADDON_VERSION }} \
            ./addon-i2c

      - name: Push image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/addon:${{ env.ADDON_VERSION }}
