name: Build Singlearch ARM64

on:
  push:
    branches: [ main ]
    paths: [ 'i2c-addon/**' ]
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set lowercase repo owner
        run: echo "REPO_OWNER_LOWERCASE=$(echo '${{ github.repository_owner }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Get addon version
        run: |
          ADDON_VERSION=$(jq -r '.version' ./addon/config.json)
          echo "ADDON_VERSION=$ADDON_VERSION" >> $GITHUB_ENV

      - name: Build singlearch ARM64
        run: |
          docker build \
            --platform linux/arm64/v8 \
            --build-arg BUILD_FROM=debian:bookworm-slim \
            -t ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/addon:${{ env.ADDON_VERSION }} \
            ./addon-i2c

      - name: Push image
        run: |
          docker push ghcr.io/${{ env.REPO_OWNER_LOWERCASE }}/addon:${{ env.ADDON_VERSION }}